# Generated by Django 4.2.7 on 2025-07-23 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la empresa"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de contacto"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Mexico_City",
                        max_length=50,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="es", max_length=5, verbose_name="Idioma"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("basic", "Básico"),
                            ("professional", "Profesional"),
                            ("enterprise", "Empresarial"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=5, verbose_name="Máximo de usuarios"),
                ),
                (
                    "max_products",
                    models.IntegerField(
                        default=1000, verbose_name="Máximo de productos"
                    ),
                ),
                (
                    "trial_ends",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin del trial"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.CreateModel(
            name="UserTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("manager", "Gerente"),
                            ("user", "Usuario"),
                            ("viewer", "Solo Lectura"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Tenant",
                "verbose_name_plural": "Usuarios-Tenants",
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
