# Generated by Django 4.2.7 on 2025-07-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
    ]
