# Generated by Django 4.2.7 on 2025-07-10 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de empresa')),
                ('document_type', models.CharField(choices=[('cedula', 'Cédula'), ('rif', 'RIF'), ('passport', 'Pasaporte'), ('other', 'Otro')], default='cedula', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('country', models.CharField(default='Venezuela', max_length=100, verbose_name='País')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito')),
                ('payment_terms', models.PositiveIntegerField(default=0, verbose_name='Términos de pago (días)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento personalizado (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Grupo de cliente',
                'verbose_name_plural': 'Grupos de clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contacto de cliente',
                'verbose_name_plural': 'Contactos de clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Facturación'), ('shipping', 'Envío'), ('work', 'Trabajo'), ('other', 'Otra')], max_length=20, verbose_name='Tipo de dirección')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('country', models.CharField(default='Venezuela', max_length=100, verbose_name='País')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dirección de cliente',
                'verbose_name_plural': 'Direcciones de clientes',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customergroup', verbose_name='Grupo'),
        ),
    ]
