# Generated by Django 4.2.7 on 2025-07-23 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("reason", models.TextField(verbose_name="Motivo del ajuste")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de inventario",
                "verbose_name_plural": "Ajustes de inventario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad reservada"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productvariant",
                        verbose_name="Variante",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "ordering": ["name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrada"),
                            ("out", "Salida"),
                            ("transfer", "Transferencia"),
                            ("adjustment", "Ajuste"),
                            ("sale", "Venta"),
                            ("purchase", "Compra"),
                            ("return", "Devolución"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Cantidad")),
                (
                    "quantity_before",
                    models.PositiveIntegerField(verbose_name="Cantidad anterior"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(verbose_name="Cantidad posterior"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Motivo"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                        verbose_name="Stock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Stock bajo"),
                            ("out_of_stock", "Sin stock"),
                            ("overstock", "Sobrestock"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de alerta",
                    ),
                ),
                ("threshold", models.PositiveIntegerField(verbose_name="Umbral")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resuelto en"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                        verbose_name="Stock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de stock",
                "verbose_name_plural": "Alertas de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.warehouse",
                verbose_name="Almacén",
            ),
        ),
        migrations.CreateModel(
            name="InventoryAdjustmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(verbose_name="Cantidad anterior"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(verbose_name="Cantidad posterior"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo específico"
                    ),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventoryadjustment",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                        verbose_name="Stock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento de ajuste",
                "verbose_name_plural": "Elementos de ajuste",
            },
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.warehouse",
                verbose_name="Almacén",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={
                ("tenant", "product_variant", "warehouse"),
                ("tenant", "product", "warehouse"),
            },
        ),
    ]
