# Generated by Django 4.2.7 on 2025-07-13 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de empresa')),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial')),
                ('document_type', models.CharField(choices=[('rif', 'RIF'), ('cedula', 'Cédula'), ('passport', 'Pasaporte'), ('other', 'Otro')], default='rif', max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('supplier_type', models.CharField(choices=[('manufacturer', 'Fabricante'), ('distributor', 'Distribuidor'), ('wholesaler', 'Mayorista'), ('retailer', 'Minorista'), ('service', 'Servicio'), ('other', 'Otro')], default='distributor', max_length=20, verbose_name='Tipo de proveedor')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('contact_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('country', models.CharField(default='Venezuela', max_length=100, verbose_name='País')),
                ('payment_terms', models.PositiveIntegerField(default=30, verbose_name='Términos de pago (días)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('delivery_time', models.PositiveIntegerField(default=7, verbose_name='Tiempo de entrega (días)')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedido mínimo')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Proveedor preferido')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Calificación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Categoría de proveedor',
                'verbose_name_plural': 'Categorías de proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Móvil')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensión')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de proveedor',
                'verbose_name_plural': 'Contactos de proveedores',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliercategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=100, verbose_name='SKU del proveedor')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nombre según proveedor')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de costo')),
                ('minimum_quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad mínima')),
                ('lead_time', models.PositiveIntegerField(default=7, verbose_name='Tiempo de entrega (días)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Proveedor preferido para este producto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto de proveedor',
                'verbose_name_plural': 'Productos de proveedores',
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
